package server;

public enum ResponseType {
    BEGIN_XACTION_SUCCESS,
    END_XACTION_SUCCESS,
    INSERT_SUCCESS,
    INSERT_KEY_EXISTS,
    DELETE_SUCCESS,
    DELETE_KEY_DOES_NOT_EXIST,
    GET_SUCCESS,
    GET_KEY_DOES_NOT_EXISTS,
    GET_FAILURE,
    UPDATE_SUCESS,
    UPDATE_FAILURE,
    RANGE_FAILURE,
    RANGE_SUCCESS,
    COMMIT_SUCCESS,
    ROLLBACK_SUCCESS,
    UNEXPECTED_FAILURE,
    INVALID_REQUEST,
    RESTART
}
